-- http://blog.jobbole.com/96225/
-- https://ro-che.info/articles/2014-04-24-lens-unidiomatic.html
-- https://artyom.me/lens-over-tea-1
-- https://www.schoolofhaskell.com/user/tel/lenses-from-scratch
